### ISSUE TITLE
Setting file decision logger fails due to wrong condition in if statement

### ISSUE THREAD

**Issue by LV-8** [aserto-dev/helm#16]
https://github.com/aserto-dev/helm/blob/a275a66b0fb6020add664173ae3b677e1a41c8e5/charts/topaz/templates/_helpers.tpl#L338C14-L338C21

Description:
Tried to setup a decision file logger which failed due to "either decisionLogs.file or decisionLogs.remote must be set"

**Comment by ronenh** [comment]
Thanks for reporting the issue @LV-8. It has been fixed in v0.1.2 of the topaz chart.
